config/routes.rb
BlogApp::Application.routes.draw do

  get "newcontroller/new"

  get "newcontroller/create"

  get "newcontroller/index"

  get "newcontroller/edit"

  get "newcontroller/destroy"

  root :to => "posts#index"

  resources :users
  resources :sessions
  resources :posts, :only => [:index, :show] do
    member do
      post :add_comment
    end
  end

  
  namespace :author do
    resources :posts
  end

  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

  validates_presence_of :post, :body, :commenter_name
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  validates_presence_of :user, :title, :content
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts

  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :name, :username, :email
  validates_presence_of :password, :on => :create
  validates_uniqueness_of :username, :email
  validates_length_of :username, :minimum => 5, :maximum => 10
  validates_length_of :password, :minimum => 5, :maximum => 10

  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.authenticate(username, password)
    user = find_by_username(username)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user, :logged_in?

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user != nil
  end

  def check_login
    if !logged_in?
      redirect_to new_session_path
    end
  end

end

app/controllers/author/posts_controller.rb
class Author::PostsController < ApplicationController
  before_filter :check_login, :except => [:show, :add_comment]
  
  def new
    @post = current_user.posts.new
  end

  def create
    @post = current_user.posts.new(params[:post])
    if @post.save
      redirect_to author_posts_path, :notice => "Blog Entry Created!"
    else
      render :new
    end
  end

  def update
    @post = current_user.posts.find(params[:id])

    if @post.update_attributes(params[:post])
      redirect_to(@post, :notice => 'Post was successfully updated')
    else
      render :action => "edit"
    end

  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def destroy
    @post = current_user.posts.find(params[:id])

    if @post.destroy
      redirect_to author_posts_path, :notice => "Blog Entry Deleted"
    else
      redirect_to posts_path, :notice => "Delete Failed"
    end

  end

  def index
    @posts = current_user.posts.all 
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new({:post => @post})
    render :action => "show"
  end

  def add_comment
    @post = Post.find(params[:id])
    @comment = @post.comments.create(params[:comment])
    if @post.save
      redirect_to post_path(@post), :notice => "Comment Added"
    else
      render :show
    end
  end
end
 
 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:username], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to author_posts_path, :notice => "Logged in!"  # should redirect them back to their blog index page
    else
      flash[:notice] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Successfully logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_url, :notice => "Signed up succesfully!"
    else
      render "new"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/author/posts/_form.html.erb
<% form_for [:author, @post] do |f| %>
<% if @post.errors.any? %>
    <div class="error_messages">
      <h2>oops!</h2>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>
  <%= f.submit %>
<% end %>

app/views/author/posts/edit.html.erb
<h1>Edit Posts</h1>
<%= render :partial => 'author/posts/form' %>

app/views/author/posts/index.html.erb
<h2>My Posts</h2>
<ol>
  <% @posts.each do |post| %>


    <li><%= link_to post.title, post %> <%= link_to "edit", edit_author_post_path(post) %>
      <%= link_to 'Delete', [:author, post], :confirm => 'are you sure?', :method => :delete %>
      <%= form_for [:author, post], :html => {:method => :delete} do %>
      <%= submit_tag "Delete" %></li>
    
    <% end %>
  <% end %>
</ol>

<%= link_to "New Post", new_author_post_path %>

app/views/author/posts/new.html.erb
<h2>Create a new blog post</h2>

<%= render :partial => 'author/posts/form' %>

app/views/author/posts/show.html.erb
<h2>Post</h2>

<% if @post.errors.any? %>
    <div class="error_messages">
      <h2>oops!</h2>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<li><b>Title</b><br> <%= @post.title %> </li>
<li><b>Content</b><br> <%= @post.content %> </li>

<% if logged_in? %>
  <%= link_to "Edit", edit_post_path %>
  <%= link_to "Back", posts_path %>
<% end %>

<br><br>

<h2>Comments</h2>
<% form_for @comment, :url => add_comment_post_path(@post) do |f| %>
  <p>
    <%= f.label :commenter_name %>
    <%= f.text_field :commenter_name %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <%= f.submit%>
<% end %>

<ol>
  <% @post.comments.order("created_at desc").each do |comment| %>
    <h3><%= comment.commenter_name %></h3>
    <p><%= comment.body %></p>
  <% end %>
</ol>

app/views/author/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogApp</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div style="float:right; width: 600px;">
    <% if current_user %>
    Logged in as <strong><%= current_user.username %></strong> |
      <%= link_to "Logout", logout_path %>
    <% else %>
      <%= link_to "Sign up", new_user_path %> |
      <%= link_to "Login", login_path %>
    <% end %>
  </div>

  <div>
    <%= notice %>
  </div>
  <h1>Railspress</h1>
  <%= yield %>
</body>
</html>

app/views/posts/_form.html.erb
<% form_for @post do |f| %>
<% if @post.errors.any? %>
    <div class="error_messages">
      <h2>oops!</h2>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>
  <%= f.submit %>
<% end %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <h2><%= link_to post.title, post %> by <%= post.user.name %></h2>
  <p><%= post.content %></p>
<% end %>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<% form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>oops!</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </p>

  <%= f.submit %>
  
<% end %>